Exception: variable coin referenced before assignment (#2832)
* Fixed variable referenced before assignment error in source Coinpaparika, Binance, Coinbase

* Changed argument name from query to coin

* Using query instead of coin

Co-authored-by: Colin Delahunty <72827203+colin99d@users.noreply.github.com>
Co-authored-by: hjoaquim <h.joaquim@campus.fct.unl.pt>