Clarifies `openbb.stocks.ca.balance` example to include `timeframe`
Makes the example more robust as it was looking for full year results from 2022, which are still unreported for some companies.

Before:
```
openbb.stocks.ca.balance(["TSLA","F", "GE"])

Error: Timeframe selected should be one of 2017, 2018, 2019, 2020, 2021
```

Changing to:
```
openbb.stocks.ca.balance(["TSLA","F", "GE"], timeframe= '2021')
```